# Generated by Django 4.1.5 on 2023-01-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
